source 'https://rubygems.org'

gem 'fpm'
gem 'puppet', '3.8.1'
gem 'puppet-lint'
gem 'rspec-puppet'
gem 'rake'
gem 'ci_reporter_cucumber'
gem 'ci_reporter_rspec'
gem 'puppetlabs_spec_helper'
gem 'beaker-rspec'
