source 'https://rubygems.org'

gem 'fpm', '0.3.11'
gem 'puppet', '3.8.1'
gem 'puppet-lint', '1.1.0'
gem 'rspec-puppet', '2.2.0'
gem 'rake', '0.9.2.2'
gem 'ci_reporter', '1.8.4'
gem 'puppetlabs_spec_helper'
gem 'beaker-rspec'
